apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  nameResolution:
    component: "consul"
    configuration:
      client:
        #address: "consul:8500"
        address: "192.168.251.6:8500"
      selfRegister: true
